version: "3"
 
services: 
  springapi:
    build:
      context: .     
    image: springauth:1.0   
    ports:
      - 8080:8082
    networks:
      - springapi-angular 

       
  angular:
    build:
      context: https://github.com/venkatesh-buddy/Angular.git#:basic-auth/
    image: angularbasic:1.0
    ports:
      - 8083:80       
    depends_on:
      - springapi  
    networks:
      - springapi-angular
     
   
networks:
  springapi-angular: