spring:
  security:
    oauth2:
      client:
        registration:   
          google:   
            client-id: #Your client Id
            client-secret: #Your client secret
# Server configuration
server:
  port: 8080
